### PR TITLE
Shrinkwrap node_modules

### PR DESCRIPTION
**Pull request by alexeits**
**What**
`npm shrinkrwap --dev`

**Why**
To have a consistent dev environment

### CODE REVIEW

**Comment by jeremymailen** [comment]
🚀
Although I've always wondered why we shrinkwrap. We did not shrinkwrap at Trifacta (managing much more node and js code than here at Gladly) and we did not experience any configuration management issues, so long as we pinned the version in package.json, and the workflow felt smoother in development.

**Comment by jeremymailen** [comment]
Or I should say I only remember a single configuration management issue in 2 years where some module author forced a bugfix update to an existing module version on npm. That's quite frowned on though.

**Comment by jotto** [comment]
> Although I've always wondered why we shrinkwrap.

We should re-evalulate whether we still want it.

The reason, iirc, that we started using it because we blindly copied our project from a node project template.

Then, we got screwed by accidentally minor or patch upgrading... I think.. babel (formerly 6to5) and it broke our build in weird ways - so then we started `shrinkwrap` with `--dev`

**Comment by alexeits** [comment]
Closing, because apparently this is somewhat controversial.

**Pull request closed without merging**
